hugoblox:
  schema: "2.0"
  identity:
    name: Elena Sanjuan
    type: person
    tagline: ""
    description: I am a PhD candidate in Economics at CEMFI. My research focuses on applied microeconomics, with particular interests in household and labor economics.
  theme:
    mode: system
    pack: default
    colors:
      primary: "#7f65a3"
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: false
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: false
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
